services:
  web:
    image: node
    command: npm run start
    ports:
      - 3000
    environment:
      - NODE_ENV: developement
    build:
      commands:
        - npm install
        - npm run migrate-seed