//******** getAll Requests  *********

POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  getAllInstruments {
    code
  }
}

query Query {
  getAllInstruments {
    code
    user {
      firstname
      lastname
    }
  }
}

query Query {
  getAllUsers {
    nickname
  }
}

query Query {
  getAllUsers {
    nickname
    role
    instruments {
      pupitre
      code
    }
  }
}

query Query {
  getAllSuits {
    label
    gender
  }
}


//******** getOne Requests  *********


POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetUserById($getUserByIdId: ID!) {
  getUserById(id: $getUserByIdId) {
    nickname
    instruments {
      code
    }
  }
}

{
  "getUserByIdId": "2"
}
//-------------------------------------------------

POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetInstrumentById($getInstrumentByIdId: ID!) {
  getInstrumentById(id: $getInstrumentByIdId) {
    code
    pupitre
  }
}

{
  "getInstrumentByIdId": "34"
}

//-------------------------------------------------

POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetInstrumentById($getInstrumentByIdId: ID!) {
  getInstrumentById(id: $getInstrumentByIdId) {
    code
    pupitre
    user {
      nickname
    }
  }
}

{
  "getInstrumentByIdId": "27"
}

POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetSuitById($getSuitByIdId: ID!) {
  getSuitById(id: $getSuitByIdId) {
    label
  }
}

{
  "getSuitByIdId": "1"
}


POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetUserById($getUserByIdId: ID!) {
  getUserById(id: $getUserByIdId) {
    firstname
  }
}

{
  "getUserByIdId": "24"
}

