//*******CREATE***********

POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation AddUser($input: UserInput) {
  addUser(input: $input) {
    lastname
    firstname
    nickname
    email
    password
    address
    city
  }
}

{
  "input": {
    "lastname": "Vandamme",
    "firstname": "Jean-Claude",
    "nickname": "JCVD",
    "email": "jcvd@email.com",
    "password": "password",
    "address": "adresse test",
    "city": "cityTest"
  }
}



POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation AddUser($input: InstrumentInput) {
  addInstrument(input: $input) {
    code
    pupitre
  }
}

{
  "input": {
    "code": "CC-test",
    "pupitre": "Caixa"
  }
}



POST http://localhost:3000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation AddSuit($input: SuitInput) {
  addSuit(input: $input) {
    label
    gender
  }
}

{
  "input": {
    "label": "NH2022",
    "gender": "Mixte"
  }
}


//************ UPDATE *************

