type Instrument {
  id: ID!
  code: String!
  pupitre: String
  observation: String
  depth: Int
  rods: Int
  weight: Float
  sticker: Boolean
  user: User
  created_at: DateTime!
  updated_at: DateTime
}

input InstrumentInput {
  code: String!
  pupitre: String
  observation: String
  depth: Int
  rods: Int
  weight: Float
  sticker: Boolean
}
