"""
List of Mutation
A mutation is the ensemble of any modification of the initial database 
"""
type Mutation {
  addUser(input: UserInput): User
  addInstrument(input: InstrumentInput): Instrument
  addSuit(input: SuitInput): Suit

  deleteSuit(id: ID!): Boolean!
  deleteUser(id: ID!): Boolean!
  deleteInstrument(id: ID!): Boolean!

  updateSuit(id: ID!, input: SuitInput): Suit
  updateUser(id: ID!, input: UserInput): User
  updateInstrument(id: ID!, input: InstrumentInput): Instrument

  loginUser(input: LoginInput): LoginReturn

  resetPassword(token: String!, newPassword: String!): ResetPasswordResult!

  updatePassword(input: PasswordInput! ): User
}
