"""
List of Query
"""
type Query {
  getAllInstruments: [Instrument]
  getAllUsers: [User]
  getAllSuits: [Suit]

  getInstrumentById(id: ID!): Instrument
  getUserById(id: ID!): User
  getSuitById(id: ID!): Suit

  getSuitsByUser(id: ID!): [Suit]

askResetPassword(email: String!): ResetPasswordResponse!
  verifyResetPasswordToken(token: String!): TokenValidation!
}
