"""
When you wrote new method in with graphQl, you have to define them with a type sytle sheet, here's the one for the resetPasword, because it's nedd to CRUD the database
"""

type ResetPasswordResponse {
    message: String!
  }

"""
Our method use a new token to be secure. If none token is provide, it will receive a false input and refuse the operation of the resetPassword method 
"""

  type TokenValidation {
    valid: Boolean!
  }


  type ResetPasswordResult {
    success: Boolean!
    message: String
  }