"""
Instead of wroting a comparision string in Javascript to make some sorting by gender, we have decided to create Enum for Gender (by user)
"""

enum Gender {
    F
    M
    Mixte
}


"""
Definition of the user Type, based on the database value
"""

type Suit {
    id: ID! 
    label: String!
    gender: Gender
    observation: String 
    quantity_s: Int
    quantity_m: Int
    quantity_l:Int
    quantity_xl: Int
    quantity_xxl: Int
    quantity_xxxl: Int
    users: [User]
    total: Int
}

"""
Type for the input, the necessary value are followed by the ! symbol
"""
input SuitInput {
    label: String!
    gender: Gender
    observation: String 
    quantity_s: Int
    quantity_m: Int
    quantity_l:Int
    quantity_xl: Int
    quantity_xxl: Int
    quantity_xxxl: Int
}