"""
Instead of wroting a comparision string in Javascript to make some sorting by gender, we have decided to create Enum for Gender  and Size (of suits)
"""


enum Gender {
  F
  M
  Mixte
}

enum Size {
  S
  M
  L
  XL
  XXL
  XXXL
}

"""
Definition of the user Type, based on the database value
"""

type User {
  id: ID!
  url_img: String
  lastname: String!
  firstname: String
  nickname: String
  email: String!
  password: String
  birthdate: Date
  phone: String
  address: String
  address_2: String
  zip_code: String
  city: String
  gender: Gender
  top_size: Size
  bottom_size: Size
  subscription: Boolean
  deposit: Boolean
  role: String
  created_at: DateTime
  updated_at: DateTime
  instruments: [Instrument]
  instrument: Instrument
  suits: [Suit]
}

"""
Type for the input, the necessary value are followed by the ! symbol
"""

input UserInput {
  url_img: String
  lastname: String!
  firstname: String
  nickname: String
  email: String!
  password: String
  birthdate: Date
  phone: String
  address: String
  address_2: String
  zip_code: String
  city: String
  gender: Gender
  top_size: Size
  bottom_size: Size
  subscription: Boolean
  deposit: Boolean
  role: String
  instrument_id: ID
}

input PasswordInput {
  password: String
  id : 
}

type PasswordReturn {
  user: ID!
  password: String
}