""" Type of User """

enum Gender {
  F
  M
  Mixte
}

enum Size {
  S
  M
  L
  XL
  XXL
  XXXL
}

type User {
  id: ID!
  url_img: String
  lastname: String!
  firstname: String
  nickname: String
  email: String!
  password: String
  birthdate: Date
  phone: String
  address: String
  address_2: String
  zip_code: String
  city: String
  gender: Gender
  top_size: Size
  bottom_size: Size
  subscription: Boolean
  deposit: Boolean
  role: String
  created_at: DateTime
  updated_at: DateTime
  instruments: [Instrument]
  instrument: Instrument
  suits: [Suit]
}

input UserInput{
  url_img: String
  lastname: String!
  firstname: String
  nickname: String
  email: String!
  password: String
  birthdate: Date
  phone: String
  address: String
  address_2: String
  zip_code: String
  city: String
  gender: Gender
  top_size: Size
  bottom_size: Size
  subscription: Boolean
  deposit: Boolean
  role: String
  instrument_id: ID
}

