type User {
    id: Int 
    url_img:String
    lastname:String 
    firstname: String 
    nickname: String 
    email: String
    password: String 
    birthdate: Int 
    phone: String
    address: String 
    address_2: String 
    zip_code: String
    city: String
    gender: String
    top_size: String
    bottom_size:String
    subscription: Boolean
    deposit: Boolean
    role: String
    created_at: Int
    updated_at: Int
    instrument : [Instrument]
    userHasSuit: [UserHasSuit]
}